### PR TITLE
gremlinpython v3.5.2

### PR DESCRIPTION
**Pull request by ChouUn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- closes #6

### CODE REVIEW

**Comment by ChouUn** [comment]
@conda-forge-admin, please ping team

**Comment by ChouUn** [comment]
@conda-forge-admin, please ping conda-forge/staged-recipes

**Comment by Luxxii** [comment]
Looks good to me. It is building locally and it looks like the CI is also able to do so too. Sorry for the delay, the initial update PR in January got lost in my todos...  

@ChouUn Please reference me directly if i am not responding again!

**Comment by ChouUn** [comment]
@Luxxii well, I thought you'd get an email notification~

**Pull request merged**
